version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: devmate-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: devmate_user
      POSTGRES_PASSWORD: devmate_1234
      POSTGRES_DB: devmate

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devmate_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

